version: 2
jobs:
  mxe-requirements:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-requirements:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-requirements:latest -t openscad/mxe-requirements:latest mxe/mxe-requirements
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-requirements:latest
  mxe-x86_64-gcc:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-x86_64-gcc:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-x86_64-gcc:latest -t openscad/mxe-x86_64-gcc:latest mxe/mxe-x86_64-gcc
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-x86_64-gcc:latest
  mxe-x86_64-deps:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-x86_64-deps:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-x86_64-deps:latest -t openscad/mxe-x86_64-deps:latest mxe/mxe-x86_64-deps
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-x86_64-deps:latest
  mxe-openscad:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-openscad:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-openscad:latest -t openscad/mxe-openscad:latest mxe/mxe-openscad
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-openscad:latest
workflows:
  version: 2
  build:
    jobs:
      - mxe-requirements
      - mxe-x86_64-gcc:
         requires:
           - mxe-requirements
      - mxe-x86_64-deps:
         requires:
           - mxe-x86_64-gcc
      - mxe-openscad:
         requires:
           - mxe-x86_64-deps
