version: 2
jobs:
  appimage-x86_64-base:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build AppImage (x86_64) base image
          no_output_timeout: 18000
          command: |
              docker pull openscad/appimage-x86_64-base:latest || true
              #docker build --cache-from openscad/appimage-x86_64-base:latest -t openscad/appimage-x86_64-base:latest appimage/appimage-x86_64-base
              docker build -t openscad/appimage-x86_64-base:latest appimage/appimage-x86_64-base
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/appimage-x86_64-base:latest
  appimage-x86_64-openscad:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build OpenSCAD AppImage (x86_64)
          no_output_timeout: 18000
          command: |
              mkdir -p /tmp/out
              docker build -t openscad/appimage-x86_64-openscad:latest --build-arg OPENSCAD_VERSION="$(date +%Y.%m.%d).appimage${CIRCLE_BUILD_NUM}" appimage/appimage-x86_64-openscad
              docker run openscad/appimage-x86_64-openscad:latest | tar -x -v -C /tmp/out
      - store_artifacts:
          path: /tmp/out
          destination: 64-bit
  appimage-arm64v8-base:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build AppImage (arm64v8) base image
          no_output_timeout: 18000
          command: |
              docker pull openscad/appimage-arm64v8-base:latest || true
              docker build --cache-from openscad/appimage-arm64v8-base:latest -t openscad/appimage-arm64v8-base:latest appimage/appimage-arm64v8-base
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/appimage-arm64v8-base:latest
  mxe-requirements:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE base image
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-requirements:latest || true
              docker build --cache-from openscad/mxe-requirements:latest -t openscad/mxe-requirements:latest mxe/mxe-requirements
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-requirements:latest
  mxe-x86_64-gcc:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE gcc (64bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-x86_64-gcc:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-x86_64-gcc:latest -t openscad/mxe-x86_64-gcc:latest --build-arg JOBS=4 mxe/mxe-x86_64-gcc
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-x86_64-gcc:latest
  mxe-x86_64-deps:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE dependencies 1 (64bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-x86_64-deps:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-x86_64-gcc:latest --cache-from openscad/mxe-x86_64-deps:latest -t openscad/mxe-x86_64-deps:latest --build-arg JOBS=4 mxe/mxe-x86_64-deps
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-x86_64-deps:latest
  mxe-x86_64-deps2:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE dependencies 2 (64bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-x86_64-deps2:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-x86_64-gcc:latest --cache-from openscad/mxe-x86_64-deps:latest --cache-from openscad/mxe-x86_64-deps2:latest -t openscad/mxe-x86_64-deps2:latest --build-arg JOBS=4 mxe/mxe-x86_64-deps2
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-x86_64-deps2:latest
  mxe-x86_64-gui:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE GUI (64bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-x86_64-gui:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-x86_64-gcc:latest --cache-from openscad/mxe-x86_64-deps:latest --cache-from openscad/mxe-x86_64-gui:latest -t openscad/mxe-x86_64-gui:latest --build-arg JOBS=4 mxe/mxe-x86_64-gui
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-x86_64-gui:latest
  mxe-x86_64-openscad:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE OpenSCAD (64bit)
          no_output_timeout: 18000
          command: |
              mkdir -p /tmp/out
              docker build -t openscad/mxe-x86_64-openscad:latest --build-arg OPENSCAD_VERSION="$(date +%Y.%m.%d).ci${CIRCLE_BUILD_NUM}" --build-arg JOBS=4 mxe/mxe-x86_64-openscad
              docker run openscad/mxe-x86_64-openscad:latest | tar -x -v -C /tmp/out
      - store_artifacts:
          path: /tmp/out
          destination: 64-bit
  mxe-i686-gcc:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE gcc (32bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-i686-gcc:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-i686-gcc:latest -t openscad/mxe-i686-gcc:latest --build-arg JOBS=4 mxe/mxe-i686-gcc
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-i686-gcc:latest
  mxe-i686-deps:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE dependencies 1 (32bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-i686-deps:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-i686-gcc:latest --cache-from openscad/mxe-i686-deps:latest -t openscad/mxe-i686-deps:latest --build-arg JOBS=4 mxe/mxe-i686-deps
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-i686-deps:latest
  mxe-i686-deps2:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE dependencies 2 (32bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-i686-deps2:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-i686-gcc:latest --cache-from openscad/mxe-i686-deps:latest --cache-from openscad/mxe-i686-deps2:latest -t openscad/mxe-i686-deps2:latest --build-arg JOBS=4 mxe/mxe-i686-deps2
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-i686-deps2:latest
  mxe-i686-gui:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE GUI (32bit)
          no_output_timeout: 18000
          command: |
              docker pull openscad/mxe-i686-gui:latest || true
              docker build --cache-from openscad/mxe-requirements:latest --cache-from openscad/mxe-i686-gcc:latest --cache-from openscad/mxe-i686-deps:latest --cache-from openscad/mxe-gui:latest -t openscad/mxe-i686-gui:latest --build-arg JOBS=4 mxe/mxe-i686-gui
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push openscad/mxe-i686-gui:latest
  mxe-i686-openscad:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build MXE OpenSCAD (32bit)
          no_output_timeout: 18000
          command: |
              mkdir -p /tmp/out
              docker build -t openscad/mxe-i686-openscad:latest --build-arg OPENSCAD_VERSION="$(date +%Y.%m.%d).ci${CIRCLE_BUILD_NUM}" --build-arg JOBS=4 mxe/mxe-i686-openscad
              docker run openscad/mxe-i686-openscad:latest | tar -x -v -C /tmp/out
      - store_artifacts:
          path: /tmp/out
          destination: 32-bit
workflows:
  version: 2
  build:
    jobs:
      - appimage-x86_64-base
      - appimage-x86_64-openscad:
         requires:
           - appimage-x86_64-base
      - mxe-requirements
      - mxe-x86_64-gcc:
         requires:
           - mxe-requirements
           - mxe-i686-gcc
      - mxe-x86_64-deps:
         requires:
           - mxe-x86_64-gcc
      - mxe-x86_64-deps2:
         requires:
           - mxe-x86_64-deps
      - mxe-x86_64-gui:
         requires:
           - mxe-x86_64-deps2
      - mxe-x86_64-openscad:
         requires:
           - mxe-x86_64-gui
      - mxe-i686-gcc:
         requires:
           - mxe-requirements
      - mxe-i686-deps:
         requires:
           - mxe-i686-gcc
      - mxe-i686-deps2:
         requires:
           - mxe-i686-deps
      - mxe-i686-gui:
         requires:
           - mxe-i686-deps2
      - mxe-i686-openscad:
         requires:
           - mxe-i686-gui
