version: 2
jobs:
  mxe-requirements:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-requirements:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-requirements:latest -t openscad/mxe-requirements:latest mxe/mxe-requirements
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-requirements:latest
  mxe-x86_64-gcc:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-x86_64-gcc:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-x86_64-gcc:latest -t openscad/mxe-x86_64-gcc:latest mxe/mxe-x86_64-gcc
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-x86_64-gcc:latest
  mxe-x86_64-deps:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-x86_64-deps:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-x86_64-deps:latest -t openscad/mxe-x86_64-deps:latest mxe/mxe-x86_64-deps
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-x86_64-deps:latest
  mxe-x86_64-openscad:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-x86_64-openscad:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-x86_64-openscad:latest -t openscad/mxe-x86_64-openscad:latest mxe/mxe-x86_64-openscad
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-x86_64-openscad:latest
      - run:
          command: mkdir -p /out && cp -v /openscad/mingw32.static.posix/OpenSCAD-*-x86-64* /out/
      - store_artifacts:
          path: /out
          destination: 64-bit
  mxe-i686-gcc:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-i686-gcc:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-i686-gcc:latest -t openscad/mxe-i686-gcc:latest mxe/mxe-i686-gcc
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-i686-gcc:latest
  mxe-i686-deps:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-i686-deps:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-i686-deps:latest -t openscad/mxe-i686-deps:latest mxe/mxe-i686-deps
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-i686-deps:latest
  mxe-i686-openscad:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker pull openscad/mxe-i686-openscad:latest || true
      - run:
          command: docker build --cache-from openscad/mxe-i686-openscad:latest -t openscad/mxe-i686-openscad:latest mxe/mxe-i686-openscad
          no_output_timeout: 18000
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push openscad/mxe-i686-openscad:latest
      - run:
          command: mkdir -p /out && cp -v /openscad/mingw32.static.posix/OpenSCAD-*-x86-32* /out/
      - store_artifacts:
          path: /out
          destination: 32-bit
workflows:
  version: 2
  build:
    jobs:
      - mxe-requirements
      - mxe-x86_64-gcc:
         requires:
           - mxe-requirements
      - mxe-x86_64-deps:
         requires:
           - mxe-x86_64-gcc
      - mxe-x86_64-openscad:
         requires:
           - mxe-x86_64-deps
      - mxe-i686-gcc:
         requires:
           - mxe-requirements
      - mxe-i686-deps:
         requires:
           - mxe-i686-gcc
#      - mxe-i686-openscad:
#         requires:
#           - mxe-i686-deps
